name: test
on:
  push:
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate@sha256:077a2aada1c508923e4e36b68f7efe3ec013a797da8aed352afd98fb0e1b4c60
      options: --user root
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: ls -lah
      - run: renovate-config-validator --strict *.json5
