name: test
on:
  push:
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate@sha256:2ccc5b1f0340593c40e1598547aa98feee4e521a0906a423fe0be0431a733dfa
      options: --user root
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: ls -lah
      - run: renovate-config-validator --strict *.json5
