name: test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:43.195@sha256:6b830e2d780964b41899c7efca4c3b1f1b59d1e4fc960aedd0a100de4a0910ab
      options: --user root
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: ls -lah
      - run: renovate-config-validator --strict *.json5
